name: moor2csv_example
publish_to: none
description: Example to show how to use moor2csv package.
version: 2.0.0
homepage: https://github.com/Dhi13man/moor2csv

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  moor2csv:
    git:
      url: "git@github.com:Dhi13man/moor2csv.git"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Only For testing and examples. Not needed by package itself to work.
  drift_dev: ^1.0.0
  sqflite: ^2.2.0+3
  sqlite3_flutter_libs: ^0.5.11+1
  sqflite_common_ffi: ^2.2.0+1
  build_runner: ^2.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
