name: moor2csv
description: Supporting package for SQL or Moor that allows the easy export of SQL based Moor databases to CSV form, for external storage or sharing. Works on all platforms other than Web.
version: 1.5.4
homepage: https://github.com/Dhi13man/moor2csv

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^4.3.0
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Only For testing and examples. Not needed by package itself to work.
  moor_generator: ^4.3.0
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.4.3
  sqflite_common_ffi: ^2.0.0
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
