name: moor2csv
description: Supporting package for Moor that allowing the easy export of SQL based Moor database to CSV form for external storage or sharing. Works on all platforms other than Web.
version: 1.0.3
homepage: https://github.com/Dhi13man/moor2csv

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^3.4.0
  path_provider: ^1.6.22
  permission_handler: ^5.0.1+1

  # Only For testing and examples. Not needed by package itself to work.
  # sqflite: ^1.3.2+1
  # sqlite3_flutter_libs: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Only For testing and examples. Not needed by package itself to work.
  moor_generator: ^3.4.0
  build_runner: ^1.10.4
  sqflite_common_ffi: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
